[book]
authors = ["MoneroRus","Mr.Pickles"]
language = "ru"
multilingual = false
src = "src"
title = "Moneropedia"

[build]
create-missing = false
preprocess = ["links", "index"]

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
no-section-label = true
mathjax-support = true
git-repository-url = "https://github.com/xmr-ru/moneropedia"
git-repository-icon = "fa-github"
